### ISSUE TITLE
PRP$ lemma differences between EWT and GUM

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-EWT#331] opened 2022-06-15 03:22 UTC
Lemmatization of "our", "their", "her", etc 

@amir-zeldes 

EWT: kind of weird that our->we and my->my instead of me, anyway

```
# sent_id = weblog-blogspot.com_alaindewitt_20060924104100_ENG_20060924_104100-0006
26      our     we      PRON    PRP$    Number=Plur|Person=1|Poss=Yes|PronType=Prs      27      nmod:poss       27:nmod:poss    _
32      my      my      PRON    PRP$    Number=Sing|Person=1|Poss=Yes|PronType=Prs      35      nmod:poss       35:nmod:poss    _
```

GUM:

```
# sent_id = GUM_academic_theropod-23
14      our     our     PRON    PRP$    Number=Plur|Person=1|Poss=Yes|PronType=Prs      15      nmod:poss       15:nmod:poss    Entity=(125-abstract-new-cf8-2-...

# sent_id = GUM_conversation_blacksmithing-22
5       my      my      PRON    PRP$    Number=Sing|Person=1|Poss=Yes|PronType=Prs      7       nmod:poss       7:nmod:poss     Entity=(23-object-giv:inact-cf2-3-coref(1-person-giv:act-cf1-1-ana)
```

**Comment by nschneid** [comment] 2022-06-15 03:30
Duplicate of UniversalDependencies/docs#517

**Closed by nschneid** 2022-06-15 03:30 UTC

**Comment by amir-zeldes** [comment] 2022-06-15 17:02
Thanks for reporting - indeed the GUM behavior is intentional, see discussion in the other thread.
