### ISSUE TITLE
Annotation errors

### ISSUE THREAD

**Issue by James-Decatur** [UniversalDependencies/UD_English-EWT#316] opened 2022-04-28 14:36 UTC
When working with Joakim Nivre, we discovered annotation errors that led to the creation of non-projective dependencies ('udapi' can help you visualize and confirm).

- Sentences, where the non-projective dependency is a 'cc' and the head, is a 'conj'

File: en_ewt-ud-dev, Sent #922: newsgroup-groups.google.com_homeopathyclinic_46a87f7e5ce279d5_ENG_20051107_133800-0008
File: en_ewt-ud-test, Sent #153: weblog-blogspot.com_aggressivevoicedaily_20060811122000_ENG_20060811_122000-0042
File: en_ewt-ud-test, Sent #1264: answers-20111107035344AAdi9dS_ans-0003
File: en_ewt-ud-test, Sent #1465: answers-20111108111112AAAjhoy_ans-0010
File: en_ewt-ud-train, Sent #151: weblog-juancole.com_juancole_20030911085700_ENG_20030911_085700-0023
File: en_ewt-ud-train, Sent #471: weblog-blogspot.com_rigorousintuition_20050518101500_ENG_20050518_101500-0010
File: en_ewt-ud-train, Sent #488: weblog-blogspot.com_rigorousintuition_20050518101500_ENG_20050518_101500-0027
File: en_ewt-ud-train, Sent #708: weblog-juancole.com_juancole_20040823064025_ENG_20040823_064025-0004
File: en_ewt-ud-train, Sent #734: weblog-juancole.com_juancole_20040823064025_ENG_20040823_064025-0030
File: en_ewt-ud-train, Sent #785: weblog-juancole.com_juancole_20040823064025_ENG_20040823_064025-0081
File: en_ewt-ud-train, Sent #1309: weblog-blogspot.com_alaindewitt_20060924104100_ENG_20060924_104100-0208
File: en_ewt-ud-train, Sent #2927: email-enronsent24_01-0061
File: en_ewt-ud-train, Sent #4394: email-enronsent03_01-0147
File: en_ewt-ud-train, Sent #5636: newsgroup-groups.google.com_GuildWars_086f0f64ab633ab3_ENG_20041111_173500-0020
File: en_ewt-ud-train, Sent #6085: newsgroup-groups.google.com_civicamerican_22c54c292026bfd2_ENG_20060128_072400-0019
File: en_ewt-ud-train, Sent #6124: newsgroup-groups.google.com_FOOLED_7554c5ce34a5a49e_ENG_20051012_144800-0008
File: en_ewt-ud-train, Sent #6580: newsgroup-groups.google.com_magicworld_04c89d43ff4fd6ea_ENG_20050104_152000-0040
File: en_ewt-ud-train, Sent #6741: newsgroup-groups.google.com_humanities.lit.authors.shakespeare_0018a7697318f71f_ENG_20031006_163200-0096
File: en_ewt-ud-train, Sent #6743: newsgroup-groups.google.com_humanities.lit.authors.shakespeare_0018a7697318f71f_ENG_20031006_163200-0098
File: en_ewt-ud-train, Sent #7570: answers-20111106035951AADq0Qg_ans-0012
File: en_ewt-ud-train, Sent #7717: answers-20111108080100AAJHNUK_ans-0018
File: en_ewt-ud-train, Sent #7941: answers-20111108084355AAvLpRa_ans-0003
File: en_ewt-ud-train, Sent #8308: answers-20111108105029AARU1Lf_ans-0015
File: en_ewt-ud-train, Sent #8350: answers-20111107193044AAvUYBv_ans-0010
File: en_ewt-ud-train, Sent #8385: answers-20111108111128AAwfype_ans-0008
File: en_ewt-ud-train, Sent #8514: answers-20111108083754AAEw5Xc_ans-0007
File: en_ewt-ud-train, Sent #8645: answers-20111108100419AAKZvMH_ans-0004
File: en_ewt-ud-train, Sent #8699: answers-20111108111107AAlrzok_ans-0008
File: en_ewt-ud-train, Sent #8722: answers-20111108111107AAlrzok_ans-0031
File: en_ewt-ud-train, Sent #8976: answers-20111108111031AARG57j_ans-0010
File: en_ewt-ud-train, Sent #9203: answers-20111107211742AAHZaPe_ans-0046
File: en_ewt-ud-train, Sent #9644: answers-20111108065616AAKtL2c_ans-0073
File: en_ewt-ud-train, Sent #10235: reviews-291046-0003
File: en_ewt-ud-train, Sent #10464: reviews-127157-0005
File: en_ewt-ud-train, Sent #10553: reviews-360698-0002
File: en_ewt-ud-train, Sent #10602: reviews-101398-0005
File: en_ewt-ud-train, Sent #10683: reviews-121651-0005
File: en_ewt-ud-train, Sent #11379: reviews-371300-0006
File: en_ewt-ud-train, Sent #11439: reviews-156953-0009
File: en_ewt-ud-train, Sent #11534: reviews-091704-0009
File: en_ewt-ud-train, Sent #11624: reviews-055207-0003
File: en_ewt-ud-train, Sent #11727: reviews-112579-0009
File: en_ewt-ud-train, Sent #12383: reviews-290594-0006
File: en_ewt-ud-train, Sent #12398: reviews-351561-0007

![Capture2](https://user-images.githubusercontent.com/76220465/165776934-d5eaaa47-7e6d-4b5b-ada9-a6979f9748e6.PNG)

- Sentences, where the non-projective dependency is a 'case' and the head, is a 'flat'

File: en_ewt-ud-dev, Sent #1130: answers-20111024210025AAVtDL7_ans-0001
File: en_ewt-ud-train, Sent #6887: newsgroup-groups.google.com_misc.consumers_a534e32067078b08_ENG_20060116_030800-0062

![Capture3](https://user-images.githubusercontent.com/76220465/165777221-e968ffd3-23ff-46f9-9266-353f1978fe14.PNG)

**Comment by nschneid** [comment] 2022-05-01 01:14
[cc before 1st conjunct attaches to 2nd](http://universal.grew.fr/?custom=626dded64060d)

**Comment by nschneid** [comment] 2022-05-01 02:12
The first group of errors is a duplicate of #307. The last two involving `flat` look correct in the dev branch.

**Closed by nschneid** 2022-05-01 02:12 UTC
