### ISSUE TITLE
iobj/obj (with ccomp and xcomp) consistency in matrix verb annotations

### ISSUE THREAD

**Issue by tzshi** [UniversalDependencies/UD_English-EWT#55] opened 2018-01-29 22:45 UTC
Is there some annotation guideline that I missed, or is this indeed an annotation consistency issue about the object of the following cases (ECM/control verbs)?

While most of the sentences annotate the object with `obj`, a few are annotated with `iobj`, such as:

1. 15->16 is annotated with `iobj`
```
# sent_id = email-enronsent30_01-0033
# text = Juan communicated some numbers to me and when reviewing this request would like to ask you to consider the following:
...
15	ask	ask	VERB	VB	VerbForm=Inf	13	xcomp	13:xcomp	_
16	you	you	PRON	PRP	Case=Acc|Person=2|PronType=Prs	15	iobj	15:iobj	_
17	to	to	PART	TO	_	18	mark	18:mark	_
18	consider	consider	VERB	VB	VerbForm=Inf	15	xcomp	15:xcomp	_
19	the	the	DET	DT	Definite=Def|PronType=Art	18	obj	18:obj	_
20	following	follow	VERB	VBG	VerbForm=Ger	19	amod	19:amod	SpaceAfter=No
21	:	:	PUNCT	:	_	2	punct	2:punct	_
```

2. 4->5 annotated with `iobj`
```
# sent_id = email-enronsent27_01-0058
# text = PS Your brother told me he went to 3 bowl games (when I found out that two of them were the galleryfurniture.com bowl and that one in Shreveport (I can't remember the name of it)) I realized he is a very, very sick college football fan.
...
4	told	tell	VERB	VBD	Mood=Ind|Tense=Past|VerbForm=Fin	0	root	0:root	_
5	me	I	PRON	PRP	Case=Acc|Number=Sing|Person=1|PronType=Prs	4	iobj	4:iobj	_
6	he	he	PRON	PRP	Case=Nom|Gender=Masc|Number=Sing|Person=3|PronType=Prs	7	nsubj	7:nsubj	_
7	went	go	VERB	VBD	Mood=Ind|Tense=Past|VerbForm=Fin	4	ccomp	4:ccomp	_
8	to	to	ADP	IN	_	11	case	11:case	_
9	3	3	NUM	CD	NumType=Card	11	nummod	11:nummod	_
10	bowl	bowl	NOUN	NN	Number=Sing	11	compound	11:compound	_
11	games	game	NOUN	NNS	Number=Plur	7	obl	7:obl	_
...
```

And the same time I can find (more) instances with verbs like tell and ask where the objects are annotated with `obj`.

There are more of these kinds, and can be found through [Grew](http://talc2.loria.fr/grew/#), using the following pattern:

```
pattern { 
    N1 [cat="VERB"];
    N1 -[iobj]-> N3;
    N1 -[xcomp]-> N2;
    N1 << N3;
    N3 << N2;
}
```

`iobj` X `ccomp` gives 43 occurrences,
`obj` X `ccomp` give 138,
`iobj` X `xcomp` give 20,
`obj` X `xcomp` gives 903.

**Comment by nschneid** [comment] 2018-01-30 05:06
My understanding is that the 2 examples you highlight are correct: `iobj` should be used for the non-case-marked recipient of verbs like *ask* and *tell*, even if there's no `obj` in the sentence (there may be a clausal complement).

Looking at a few `obj` + `xcomp` examples, several are verbs like *make*, *let*, and *keep* where the `xcomp` is a secondary predicate. I believe these are correct.

Looking at a few `obj` + `ccomp` examples, several are instances of *ask*, *tell*, etc. These indeed look like errors: I believe they should be changed to `iobj`. But there are some other verbs used in constructions that also match this pattern where `obj` looks correct.

**Comment by jnivre** [comment] 2018-01-30 08:12
I know that the guidelines say that iobj should be used in these cases, but I honestly now think that this was a mistake. All the usual tests indicate that these are direct objects, and their treatment as indirect objects also complicate the analysis of control for the enhanced dependencies. In fact, the original source of the problem is the choice to treat "her" as the indirect object in "he gave her a book". This is essentially a semantic analysis, identifying the indirect object with the recipient role, a type of analysis that UD otherwise rejects. All the syntactic criteria again point to "her" being the direct object and "a book" being what typologists call a secondary object (not an indirect object). UD probably does not want to introduce a special relation for secondary objects, but with hindsight it would have been much better to treat "her" as obj and "a book" as iobj, because it would not have propagated errors to other constructions. I am not sure whether this is something that can be considered as a "correction" of v2 guidelines or if we have to wait for v3.

**Comment by dan-zeman** [comment] 2018-01-30 08:23
It is English-specific, therefore I think it would not be a change of the universal v2 guidelines and it can be corrected now.

But is "a book" really "less core" than "her" in "he gave her a book"? Aren't both the objects "equally core"? If they are, shouldn't both be labeled `obj`?

**Comment by jnivre** [comment] 2018-01-30 08:30
In most dialects of English, only "her" can be passivised, for example:

she was given a book
*a book was given her

Compare this to:

a book was given to her
*she was given a book to

So it seems that the two "double object" constructions are really quite similar to alternations like "load the truck with hay" vs. "load hay on the truck", where only one thing can be the direct object at a time.

**Comment by sylvainkahane** [comment] 2018-01-30 08:45
I agree with Joakim. Same thing for relative clauses I think:

the girl I gave the book
*the book I gave her

This analysis was defended in a Bresnan 1981's paper.

**Comment by amir-zeldes** [comment] 2018-01-30 15:34
I don't think we can completely take the semantics out of it, or if we do, we might need to revise a lot of things to be more 'surfacy'. For example `xcomp` for verbs of becoming, which in stronger cased Germanic languages take what looks like a nominative:

  * I became a teacher - xcomp(became,teacher)
  * I became him (note the non-nominative appearance of the pronoun, *I became he)

In this example, I can't see an overt difference to a normal object, notwithstanding the non-passivizability. If that were to be an argument, we could switch to transitive causative xcomp with 'they made him a teacher' (and 'he was made a teacher'). If we don't use semantics, why should that be xcomp and not double obj? 

To be clear, I'm not advocating giving up xcomp here, and I do understand the semantic motivation, as well as the analogy to other Germanic languages:

  * Ich bin ein Leherer geworded (nominative, cf. *einen Lehrer, accusative)

On the other hand, I think the predicate of 'become' is very much a core argument, but is not the same thing as `obj`, so we should allow some degree of semantic reasoning in deciding what we consider 'the same'.

But maybe a better argument not to make recipients `obj` is that we generally have this information in the English treebanks, so deleting it would be a big loss! I think it can also be useful when comparing with languages that have more overt indirect object marking.

**Comment by sylvainkahane** [comment] 2018-01-30 16:26
Dative shift is a regular alternation/redistribution. It seems reasonnable to use the same strategy as for passive or causative. In _I gave her a book_, we want to say that _her_ is a true object and that it corresponds to the dative of the alternative construction (_I gave a book to her_). So a label such as `obj:datshift` could be an option.

**Comment by sylvainkahane** [comment] 2018-01-30 21:05
I would like to react to my own proposition. Such a proposition presupposes that the we have identified a base construction among the two constructions in alternation and that we can say that one is a redistribution of the other. I'm not certain that the notion of base construction is correct and that a base construction can be identified. For the active and passive voices it is quite clear because one construction is simpler and more frequent than the other, but for the dative shift I have no intuition (maybe because I'm not a native speaker). Of course if we consider that _I gave her a book_ is the base construction, the annotation changes. Maybe we should adopt a neutral annotation that does not presuppose any direction in the alternation.

**Comment by amir-zeldes** [comment] 2018-01-31 19:23
I'm not sure I like the idea of 'base construction'... A lot of constructionist and psycholinguistic work has shown that that concept is really tied to specific prototypical cases, whereas in other cases the supposedly basic variant is not basic at all. A good example in English is `X is based on Y`, which looks like a passive of `Y bases on X`. Although the latter is possible, the former is much more likely, and it would seem to be stored as the 'normal' form of that construction for speakers.

But linguistic evidence aside, I would like to avoid verbs having two things called `obj` without an ability to distinguish which one corresponds to which argument structure slot. I realize we already do this when there are multiple `obl`, but those can often be disambiguated by the preposition they govern via `case` (or in an enhanced representation). For me, `iobj` currently does the job nicely, so I don't feel a need to change it. But maybe that's just related to the applications I use the data for...

**Comment by jnivre** [comment] 2018-01-31 19:29
I don't think you need to assume a base construction to argue that the recipient should be obj in the double object construction. I also want to avoid having two obj, so the proposal would be to swap obj and iobj in the double object construction, because this is more consistent with the overall UD philosophy and makes the right prediction about things like passivisation. It also eliminates the anomaly of having iobj without obj in sentences like "she told him that ...", which otherwise appears to be an ad hoc exception.

**Comment by amir-zeldes** [comment] 2018-01-31 19:45
I agree the base construction discussion can be put the side, but I'm not so happy about having the recipient be the `obj`, because in a transfer of possession verb without a recipient, the theme would again be the object:

I gave everything!
obj(gave,everything)

This means that we can no longer rely on theme=obj, recipient=iobj, which is exactly the distinction that I care about for most applications. I'm sure others may see this differently, but from my point of view, this would be breaking something that doesn't need fixing :|

**Comment by nschneid** [comment] 2018-01-31 19:48
To echo @amir-zeldes, I think the current policy is straightforward to apply because you have parallelism in what argument `iobj` applies to:

* She told me_iobj.
* She told me_iobj the bad news_obj.
* She told me_iobj of the bad news_obl.
* She told me_iobj that something happened_ccomp.
* She told me_iobj to leave_xcomp.

**Comment by jnivre** [comment] 2018-01-31 19:55
Yes, this is a typical conflict between clauses 1-2 (sound for linguistic analysis and typology) and clauses 5-6 (understandable to non-linguists and useful for downstream NLP) in Manning's Law. I happily admit that I have a bias for the former. :)

**Comment by jnivre** [comment] 2018-01-31 21:07
On a more serious note, the problem with assuming a one-to-one mapping between grammatical relations and thematic roles is that it will fail in many other cases. For example:

(1) they loaded the truck with hay
(2) they loaded hay on the track

In (1) obj maps to goal or location, in (2) it maps to theme.

(3) the window broke
(4) he broke the window

In (3) nsubj maps to theme, in (4) it maps to agent.

If you really want to derive a semantic representation, you have to do linking properly. Assuming a consistent mapping is just wishful thinking, and therefore we might as well do proper syntax instead. :)

**Comment by gossebouma** [comment] 2018-02-01 09:17
I was going over the Dutch data for cases with obj/iobj and ccomp/xcomp and it turns out we have quite a few verbs where both annotations occur. The criterion I think is whether the NP argument can become the subject in a passive or not. So in most cases, we should be able to decide between obj and iobj per predicate. 
However, there are also a few cases where the data goes both ways, the verb 'vragen' (to ask) being a case in point. We find both

Ik (nom) werd gevraagd om te komen
I was asked to com
Mij (non-nom) werd gevraagd te komen
Aan (to) mij werd gevraagd te komen

and similar situations where the nominal argument does or does not agree with the finite auxiliary. 

Grammar purists tend to point out that only the non-nominative/ non-agreeing cases are correct here, but clearly actual usage does not always obey this rule.

**Comment by sylvainkahane** [comment] 2018-02-01 10:57
@jnivre It is also a conflict between syntax and semantics. As you recalled, a purely syntactic annotation would have decided to encode the complement that can be passived and extracted as the `obj`.

But as remarked by @amir-zeldes, if we do that we lost the link between the two possible constructions of _give_. So the questions are:

• Do we want to keep this link? Is syntax concerned by this link? Or is it essentially semantic and should it be kept at the enhanced level?

• If we want to keep it, how can we proceed?

For the active-passive alternation, UD scheme has decided to keep the link between the two constructions. The way it is done presupposes that the active construction is the base construction or at least the default construction (which is reasonnable for many languages).

**Comment by dseddah** [comment] 2018-02-01 12:23
Hi all,

one possible solution could be to encode both the canonical (the "deep" structure) and the final (the surface) realizations as it was proposed, following many other works, in our deep syntax proposals (Candito et al, 2014, [1] for the native scheme, Candito et al (2017) for the Enhanced-like UD one [2], see [3] for Marie's depling slides). 

Sylvain@ I don't think the enhanced-* scheme focuses on Semantic, from what I understood (and discussions are still ongoing anyway), it's more about having complete syntactic structures, namely all core argument relations  being represented by an actual edge. Details varie of course :)
  
[1] http://www.lrec-conf.org/proceedings/lrec2014/pdf/494_Paper.pdf
[2] http://aclweb.org/anthology/W/W17/W17-6507.pdf
[3] http://www.linguist.univ-paris-diderot.fr/~mcandito/Publications/depling17-slides.pdf

**Comment by amir-zeldes** [comment] 2018-02-01 18:44
@jnivre and @sylvainkahane I think it is no coincidence that distinct labels have emerged for both passives and ditransitives in particular. These are precisely the constructions which in English do not have overt adpositional markers, and beyond English, I think this is typologically frequently(ish?) the case as well.

The reason why the spray/load alternations are less worrisome to concerns such as Manning's clauses 5-6 is IMO the fact that the combination of predicate lemma and preposition can nicely disambiguate which argument is which. For true double objects, and especially if you have word order variation (e.g. 'give me it' next to, in some varieties/languages, 'give it me'), the label becomes rather crucial. 

Since what is being discussed, at least for English, is giving up a useful existing distinction, I feel obliged to object. On the other hand if we're just thinking of renaming things (e.g. using obj:iobj or something), then that is less crucial of course.

**Comment by dan-zeman** [comment] 2018-06-03 08:37
@amir-zeldes Yes, I think it should be about renaming things. I think it would be more appropriate to use a subtype like `obj:rcpt`, that overtly admits that this is primarily about the semantic role. (In other languages, it will be much clearer that the theme is less core than the recipient, so one may again ask what exactly `:iobj` means.) I agree with you that useful information should not be lost. This is why we now use `obl:arg` in Czech because we do not want to lose usefule distinction between arguments and adjuncts, which is not supported at the universal level of UD relations.

**Comment by dan-zeman** [comment] 2018-06-13 10:18
Better late than never :-) UDW should work.

**Comment by nschneid** [comment] 2023-04-27 01:16
Thanks!

- A few precision errors due to verbs like "reassure" and "inform". I think it's best to monitor [the list of iobj verbs](https://universal.grew.fr/?custom=6449cbe8e3b2b) and weed out false positives.
- Do the above changes handle control cases where the object is sister to xcomp (*tell us to VP*)? https://universal.grew.fr/?custom=6449c8c3a4878 (keeping in mind there should be an E:nsubj:xsubj from the embedded verb)

(Note: changes haven't propagated to the Grew-match server yet. Sometimes takes about an hour.)

**Comment by nschneid** [comment] 2023-04-27 17:08
Oh you're right—I forgot that we are including verbs that license two objects OR object+ccomp.

How about a Depedit rule: obj(Y=tell/ask/..., X) & xcomp(Y, Z) -> iobj(Y,X) & E:iobj(Y,X) & E:nsubj:xsubj(Z, X)? The list of relevant verbs can be constructed from https://universal.grew.fr/?custom=644aaaed97bac.

(I was going to say that a different enhanced dependency is needed for "promise X to Y" as "promise" is a subject control verb, but I don't see this anywhere in the data!)

**Comment by amir-zeldes** [comment] 2023-04-27 19:19
This all sounds good, but I'm confused about the edeps - I already did E:iobj in the commit, and I think E:nsubj:xsubj should already be in the data, since those edges already applied when it was plain obj. Or am I missing something?

**Comment by nschneid** [comment] 2023-04-27 21:18
You only did this for objects that the parser labeled as iobj, right? I'm suggesting to apply the rule to catch instances the parser may have missed.

You're right that E:nsubj:xsubj is there for current obj+xcomp except for [a few cases due to relative clauses](https://universal.grew.fr/?custom=644ad009751d0). There are [20 instances](https://universal.grew.fr/?custom=644ad046d0d80) with iobj where the E:nsubj:xsubj is missing.

(BTW, build.py will produce the 3 main .conllu files from source docs. I just pushed.)

**Comment by nschneid** [comment] 2023-04-29 18:26
- [ ] [easy-to-find iobj false negatives in EWT: obj pronouns](https://universal.grew.fr/?custom=644d60d4a8a5f)

**Comment by nschneid** [comment] 2023-04-29 20:54
I must admit I'm having some qualms about iobj for "allow" and "permit". While the double object construction is possible ("I will allow/permit you 3 cookies") it is rare, and often the verb is sufficiently abstract that the iobj would be a nonvolitional entity where no possession is implied ("These measures will allow the economy to grow at a healthy rate / ?These measures will allow the economy a healthy rate of growth").

**Comment by nschneid** [comment] 2023-04-29 21:45
I am guessing raising should not trigger iobj in cases like:

- newly released papers, showing **him** complicit in the airliner bombing
   * has nothing to do with showing something to him
- they believe **that** to be true

**Comment by nschneid** [comment] 2023-04-30 23:02
@amir-zeldes thoughts on "allow" and "permit" (see above)?

**Comment by amir-zeldes** [comment] 2023-04-30 23:12
? I could have sworn I commented on allow somewhere but can't see the comment now... Yes, I'm on board with allow etc., because of "allow/permit me the honor of..."

**Comment by nschneid** [comment] 2023-04-30 23:21
So TBC, "allow/permit X to Y" should always be iobj? In GUM [it's currently obj](https://universal.grew.fr/?custom=644ef79fc805d).

**Comment by nschneid** [comment] 2023-05-01 14:32
I think the underlying principle is that removing a complement (whether obj, ccomp, or xcomp) should not change the deprel of the remaining object if the meaning doesn't change. The test for iobj is whether the verb could combine it with obj or ccomp. Whether an xcomp could be present is irrelevant to the obj vs. iobj distinction. (Otherwise, we would end up with "ask him/iobj (a question/obj)" but "ask him/obj to leave/xcomp", as you point out, so the deprel for the first object would not be invariant to dropping the xcomp.)

The reason this policy feels like a stretch for "allow" and "permit" is that these USUALLY do not occur with two objects or object+ccomp. They feel like raising verbs: "we allowed him to leave" = allow(we, leave(he)) as opposed to the control interpretation allow(we, he, leave(he)). But they have an infrequent double object usage: "we'll allow him this indulgence" = allow(we, he, indulgence).

I think we need an exception for raising interpretations anyway, due to cases like

> * newly released papers, showing **him** complicit in the airliner bombing
>    - has nothing to do with showing something to him

But I'm not sure those allow ellipsis of the xcomp:

- *There was a question of whether he was complicit in the bombing, and in fact, the evidence showed him. (= showed him so, showed him complicit)
   * Compare: He wanted to leave, and we allowed him.

**Comment by amir-zeldes** [comment] 2023-05-01 15:05
Hm, OK - I think the raising argument doesn't hold for allow/permit on a formal level (you don't get the actual 'raising' behavior with expletives like with "seem" or "happen"), so I guess our guidelines force our hand here. If you really don't like it on permit/allow, then I think the only way to exempt them is by arguing that the ditransitive variants are archaic, and maintain a list of exempt verbs that these should go on. These are edge cases so I don't care too deeply which side they land on, but we should be consistent, I can implement it either way.

**Comment by nschneid** [comment] 2023-05-01 15:25
I wouldn't call them archaic. "I'll allow you three wishes" is perfectly fine.

I suppose we should just go with iobj, even though semantically it can stretch beyond typical characteristics like animacy when coupled with an infinitival xcomp. (It can even be an event: "We'll allow **the meeting** to be scheduled on Saturday.")

**Comment by amir-zeldes** [comment] 2023-05-01 16:05
> We'll allow the meeting to be scheduled on Saturday

That's completely fine by me! None of this is meant to capture semantic classes IMO - just the opposite, the corpus can now allow us to find non-person entities which function as indirect objects. There are plenty of examples in the data, also with 'give':

  * it is reasonable to give its views greater weight
  * gave it a quick tug

So I'll go with iobj for allow/permit then.

**Comment by amir-zeldes** [comment] 2023-05-01 17:35
I guess this applies to cause + xcomp too, so these should be fixed:

https://universal.grew.fr/?custom=644ff8215ebdc

**Comment by nschneid** [comment] 2023-05-01 18:09
Although I guess we can't assign all of them iobj because it's a situation like "tell"—the monotransitive could be either obj or iobj:

- I'll allow you/iobj three wishes/obj.
- I'll allow you/iobj to make three wishes.
- I'll allow three wishes/obj.
- I'll allow three wishes/obj to be made.

**Comment by nschneid** [comment] 2023-05-01 19:24
With allow/prevent/cause and one object, should the criterion be that affected entities are iobj, and everything else is obj?

- a change in the climate caused **the skies** to cloud over
- back legs were pushed in causing **the dresser** to lean into the wall

These are not animate, but they are affectees, and could occur in a double object like "cause the dresser damage". So I guess iobj. But in "I'll allow three wishes", "three wishes" is an event.

It could be ambiguous whether an entity is an affectee of causing/allowing or not:

- The airline allows one pet.
   * Interpretation where the pet is given permission to board: iobj - cf. The airline allows one pet boarding privileges
   * Interpretation where somebody is allowed to bring one pet: obj - cf. The airline allows passengers one pet

**Comment by amir-zeldes** [comment] 2023-05-01 19:35
> Although I guess we can't assign all of them iobj because it's a situation like "tell"—the sole object could be either obj or iobj

Absolutely, I'm running a script on GUM based on entity type and confirming changes one by one

> should the criterion be that affected entities are iobj

I think you can use that as a first heuristic, but no, I don't think that's the criterion. The real criterion is just 'which slot does it occupy in the ditransitive version':

  * a change in the climate caused the skies to cloud over
    * iobj, because it's the first object in the transformed version "The changed caused the sky clouding over" (admittedly awkward, but a CFG allowing "caused the sky harm" should accept it)

onversely "a change in the climate caused clouding to occur in the sky" is obj, under the same interpretation.

> It could be ambiguous whether an entity is an affectee of causing/allowing or not

Right, and again I would expect them to show up in the corresponding alternation slots in paraphrases.

**Comment by nschneid** [comment] 2023-05-01 20:41
Final EWT queries:

- [ ] [pronominal obj likely iobj](https://universal.grew.fr/?custom=64502318af129)
- [ ] [nonpronominal obj of allow/permit/cause](https://universal.grew.fr/?custom=645023d74b418)
- [ ] [other nonpronominal obj](https://universal.grew.fr/?custom=6450239b0d9ba)

**Comment by nschneid** [comment] 2023-10-28 14:00
- [ ] "thank you" should be `obj`: https://universal.grew.fr/?custom=653d13ddbc4ef

**Closed** 2023-10-28 15:37 UTC
